# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_item_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
