# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_total_item_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total_item_count',
            new_name='total_item',
        ),
    ]
