# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariationimage',
            name='name',
            field=models.CharField(default='hi', max_length=120),
            preserve_default=False,
        ),
    ]
