# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20161201_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='cat',
        ),
        migrations.AddField(
            model_name='cat',
            name='var',
            field=models.ManyToManyField(to='products.Variation'),
        ),
    ]
