# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productvariationimage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
