# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20161201_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='var',
        ),
        migrations.AddField(
            model_name='variation',
            name='color',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='size',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
