# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 02:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20161201_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='color',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variation',
            name='size',
            field=models.CharField(default=datetime.datetime(2016, 12, 2, 2, 54, 55, 717648, tzinfo=utc), max_length=120),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together=set([('size', 'color')]),
        ),
    ]
