# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170119_1610'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductFeatured',
            new_name='ProductFeaturedImage',
        ),
        migrations.RenameModel(
            old_name='ProductVariationImage',
            new_name='ProductImage',
        ),
    ]
