# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20161202_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeatured',
            name='show_price',
        ),
    ]
