# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productfeatured_show_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together=set([('size', 'color', 'product')]),
        ),
    ]
