# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20161203_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=20),
            preserve_default=False,
        ),
    ]
