# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('status', models.CharField(choices=[(b'%', b'%'), (b'$', b'$'), (b'free shipping', b'Free Shipping')], default=b'$', max_length=15)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.CouponCode'),
        ),
    ]
