# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20161208_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='name',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
