# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20170111_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
