# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='text_animation',
            field=models.CharField(blank=True, choices=[('Fade in', (('fadeIn', 'Fade In'), ('fadeInLeft', 'Fade in Left'), ('fadeInRight', 'Fade in Right'), ('fadeInUp', 'Fade in Up'), ('fadeInDown', 'Fade in Down'))), ('Flip in', (('flip', 'flip'), ('flipInX', 'Flip in X'), ('flipInY', 'Flip in Y'))), ('Zoom in', (('zoomInUp', 'Zoom In Up'), ('zoomInDown', 'Zoom In Down'), ('zoomInLeft', 'Zoom in Left'), ('zoomInRight', 'Zoom in Right'))), ('lightSpeedIn', 'Light Speed In')], max_length=10, null=True),
        ),
    ]
